import { Inter } from "next/font/google";
import "./globals.css";
import FlareCursor from "@/components/FlareCursor";
const inter = Inter({ subsets: ["latin"] });
import localFont from "next/font/local";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const atariFont = localFont({
  src: "./fonts/Atari.ttf",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={atariFont.className}>
        <FlareCursor />
        {children}
      </body>
    </html>
  );
}
